on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check and Lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy (loaded)
        run: cargo clippy --workspace --all-targets --no-default-features --features loaded -- -D warnings
      - name: Cargo clippy (linked)
        run: cargo clippy --workspace --all-targets --no-default-features --features linked -- -D warnings
      - name: Cargo clippy (all features)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Docs
        env:
          RUSTDOCFLAGS: -Dwarnings --cfg docsrs
        run: cargo +nightly doc --no-deps --workspace --all-features --document-private-items
